apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-pod-role
  namespace: argo
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch", "update"]
