apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-admin-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: nitinsuvagia
  namespace: argo
roleRef:
  kind: Role
  name: argo-workflow-admin
  apiGroup: rbac.authorization.k8s.io
