apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-admin-binding
subjects:
- kind: ServiceAccount
  name: nitinsuvagia
  namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-workflow-admin
  apiGroup: rbac.authorization.k8s.io
