---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/hostdata  # Directory on the host machine where data will be stored

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual

---
apiVersion: v1
kind: Pod
metadata:
  name: docker-pv-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ['sh', '-c', 'echo Hello, World! > /mnt/data/hello.txt && sleep 3600']
    volumeMounts:
    - name: storage
      mountPath: /mnt/data  # Path inside the container
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: host-pvc
